### ISSUE TITLE
Support for multiple selections?

### ISSUE THREAD

**Issue by kaushalmodi** [p-gen/smenu#1]
Hello,

I just tried out this neat utility and like the minimalism aspect of it.

Is there a way to do multiple selections?

Here's a trivial example (in tcsh):

    set foo=`echo "A B C" | smenu` && echo $foo

Right now, I can set `foo` to "A", "B" or "C". Is there a way so that foo can be set to something like "A\0B", "A\0C", "C\0B", or even "A\0B\0C", where `\0` is the null character?

**Comment by p-gen** [comment]
Hi,

Thank you for trying it.

Sorry, it's not possible for now but I'll think about it for the next version. Perhaps by introducing a tag/untag interactive command.

Stay tuned

**Comment by kaushalmodi** [comment]
Thank you. I will take some time, to go through the man page. It's very informative and with lot of examples. :)

**Comment by p-gen** [comment]
A new version is coming with tagging. I hope it will meet your needs.

Small demo here: https://youtu.be/WjpFCA7yy78

**Comment by kaushalmodi** [comment]
Thank you for adding this feature. It is working great!
