### ISSUE TITLE
Gentoo Linux - All Tests PASS

### ISSUE THREAD

**Issue by jlpoolen** [p-gen/smenu#11]
For posterity.  You may close this issue.

All tests PASS on Gentoo Linux (Dell Inspiron 2012?) 

      All validated tests passed successfully !
      real	15m0.557s
      user	0m2.475s
      sys	0m4.731s
      jlpoole@themis /tmp/test
      themis /tmp/tests # emerge --info
      Portage 2.3.24 (python 3.5.5-final-0, default/linux/amd64/17.0, gcc-6.4.0, glibc-2.25-r11, 4.9.16-gentoo x86_64)
      =================================================================
      System uname: Linux-4.9.16-gentoo-x86_64-Intel-R-_Core-TM-_i5_CPU_M_460_@_2.53GHz-with-gentoo-2.4.1
      KiB Mem:     5893596 total,    498560 free
      KiB Swap:     524284 total,    524284 free
      Timestamp of repository gentoo: Sat, 26 May 2018 20:30:01 +0000
      Head commit of repository gentoo: 090b200fa862768e5db2ad569d32fa42f495408b
      sh bash 4.4_p12
      ld GNU ld (Gentoo 2.26.1 p1.0) 2.26.1
      app-shells/bash:          4.4_p12::gentoo
      dev-java/java-config:     2.2.0-r4::gentoo
      dev-lang/perl:            5.24.3-r1::gentoo
      dev-lang/python:          2.7.14-r1::gentoo, 3.4.5-r1::gentoo, 3.5.5::gentoo
      dev-util/cmake:           3.9.6::gentoo
      dev-util/pkgconfig:       0.29.2::gentoo
      sys-apps/baselayout:      2.4.1-r2::gentoo
      sys-apps/openrc:          0.34.11::gentoo
      sys-apps/sandbox:         2.13::gentoo
      sys-devel/autoconf:       2.13::gentoo, 2.69-r4::gentoo
      sys-devel/automake:       1.11.6-r3::gentoo, 1.15.1-r2::gentoo
      sys-devel/binutils:       2.26.1::gentoo, 2.28-r2::gentoo, 2.29.1-r1::gentoo
      sys-devel/gcc:            4.9.4::gentoo, 5.4.0-r3::gentoo, 6.4.0-r1::gentoo
      sys-devel/gcc-config:     1.8-r1::gentoo
      sys-devel/libtool:        2.4.6-r3::gentoo
      sys-devel/make:           4.2.1::gentoo
      sys-kernel/linux-headers: 4.13::gentoo (virtual/os-headers)
      sys-libs/glibc:           2.25-r11::gentoo
      Repositories:
      
      gentoo
          location: /usr/portage
          sync-type: rsync
          sync-uri: rsync://rsync.gentoo.org/gentoo-portage
          priority: -1000
          sync-rsync-verify-metamanifest: no
          sync-rsync-extra-opts: 
      
      JLPOOLE_OVERLAY
          location: /usr/local/portage
          masters: gentoo
      
      ACCEPT_KEYWORDS="amd64"
      ACCEPT_LICENSE="* -@EULA"
      CBUILD="x86_64-pc-linux-gnu"
      CFLAGS="-march=native -O2 -pipe"
      CHOST="x86_64-pc-linux-gnu"
      CONFIG_PROTECT="/etc /usr/share/gnupg/qualified.txt"
      CONFIG_PROTECT_MASK="/etc/ca-certificates.conf /etc/dconf /etc/env.d /etc/fonts/fonts.conf /etc/gconf /etc/gentoo-release /etc/php/apache2-php7.0/ext-active/ /etc/php/apache2-php7.1/ext-active/ /etc/php/cgi-php7.0/ext-active/ /etc/php/cgi-php7.1/ext-active/ /etc/php/cli-php7.0/ext-active/ /etc/php/cli-php7.1/ext-active/ /etc/revdep-rebuild /etc/sandbox.d /etc/terminfo"
      CXXFLAGS="-march=native -O2 -pipe"
      DISTDIR="/usr/portage/distfiles"
      FCFLAGS="-O2 -pipe"
      FEATURES="assume-digests binpkg-logs config-protect-if-modified distlocks ebuild-locks fixlafiles merge-sync multilib-strict news parallel-fetch preserve-libs protect-owned sandbox sfperms strict unknown-features-warn unmerge-logs unmerge-orphans userfetch userpriv usersandbox usersync xattr"
      FFLAGS="-O2 -pipe"
      GENTOO_MIRRORS="http://gentoo.osuosl.org/ http://mirror.usu.edu/mirrors/gentoo/"
      LANG="en_US.utf8"
      LDFLAGS="-Wl,-O1 -Wl,--as-needed"
      MAKEOPTS="-j3"
      PKGDIR="/usr/portage/packages"
      PORTAGE_CONFIGROOT="/"
      PORTAGE_RSYNC_OPTS="--recursive --links --safe-links --perms --times --omit-dir-times --compress --force --whole-file --delete --stats --human-readable --timeout=180 --exclude=/distfiles --exclude=/local --exclude=/packages --exclude=/.git"
      PORTAGE_TMPDIR="/var/tmp"
      USE="X acl amd64 berkdb bindist bzip2 cli crypt cxx dbus dri fortran gdbm iconv ipv6 jpeg lock modules multilib ncurses nls nptl openmp pam pcre php readline seccomp session ssl startup-notification tcpd thunar udev unicode xattr zlib" ABI_X86="64" ALSA_CARDS="ali5451 als4000 atiixp atiixp-modem bt87x ca0106 cmipci emu10k1x ens1370 ens1371 es1938 es1968 fm801 hda-intel intel8x0 intel8x0m maestro3 trident usb-audio via82xx via82xx-modem ymfpci" APACHE2_MODULES="authn_core authz_core socache_shmcb unixd actions alias auth_basic authn_alias authn_anon authn_dbm authn_default authn_file authz_dbm authz_default authz_groupfile authz_host authz_owner authz_user autoindex cache cgi cgid dav dav_fs dav_lock deflate dir disk_cache env expires ext_filter file_cache filter headers include info log_config logio mem_cache mime mime_magic negotiation rewrite setenvif speling status unique_id userdir usertrack vhost_alias" CALLIGRA_FEATURES="karbon plan sheets stage words" COLLECTD_PLUGINS="df interface irq load memory rrdtool swap syslog" CPU_FLAGS_X86="mmx mmxext popcnt sse sse2 sse3 sse4_1 sse4_2 ssse3" ELIBC="glibc" GPSD_PROTOCOLS="ashtech aivdm earthmate evermore fv18 garmin garmintxt gpsclock isync itrax mtk3301 nmea ntrip navcom oceanserver oldstyle oncore rtcm104v2 rtcm104v3 sirf skytraq superstar2 timing tsip tripmate tnt ublox ubx" INPUT_DEVICES="evdev synaptics" KERNEL="linux" LCD_DEVICES="bayrad cfontz cfontz633 glk hd44780 lb216 lcdm001 mtxorb ncurses text" LIBREOFFICE_EXTENSIONS="presenter-console presenter-minimizer" OFFICE_IMPLEMENTATION="libreoffice" PHP_TARGETS="php5-6 php7-0" POSTGRES_TARGETS="postgres9_5" PYTHON_SINGLE_TARGET="python3_5" PYTHON_TARGETS="python2_7 python3_5" RUBY_TARGETS="ruby23" USERLAND="GNU" VIDEO_CARDS="amdgpu fbdev intel nouveau radeon radeonsi vesa dummy v4l" XFCE_PLUGINS="brightness clock trash" XTABLES_ADDONS="quota2 psd pknock lscan length2 ipv4options ipset ipp2p iface geoip fuzzy condition tee tarpit sysrq steal rawnat logmark ipmark dhcpmac delude chaos account"
      Unset:  CC, CPPFLAGS, CTARGET, CXX, EMERGE_DEFAULT_OPTS, INSTALL_MASK, LC_ALL, LINGUAS, PORTAGE_BUNZIP2_COMMAND, PORTAGE_COMPRESS, PORTAGE_COMPRESS_FLAGS, PORTAGE_RSYNC_EXTRA_OPTS
      
      themis /tmp/tests #

**Comment by p-gen** [comment]
:-D
