### ISSUE TITLE
Fix signal handler

### ISSUE THREAD

**Issue by elfring** [p-gen/smenu#13]
The function “[fputs](http://pubs.opengroup.org/onlinepubs/9699919799/functions/fputs.html "Put a string on a stream.")” does not belong to the list of [async-signal-safe functions](https://www.securecoding.cert.org/confluence/display/c/SIG30-C.+Call+only+asynchronous-safe+functions+within+signal+handlers "Call only asynchronous-safe functions within signal handlers.").
I guess that a different program design will be needed for your function “[sig_handler](https://github.com/p-gen/smenu/blob/185ae7421c008e597c9f0de74cd53dbe97e51cf3/smenu.c#L6025 "Update candidate")”.

**Comment by p-gen** [comment]
Hi, the `fputs` are there to print fatal error messages and are almost immediately followed by an `exit(EXIT_FAILURE);` so I guess the risk is low.

I'll however add it to my TODO list. Thank you for your remark.

**Comment by elfring** [comment]
Would you like to consider other software design options?
- [sigwaitinfo()](http://pubs.opengroup.org/onlinepubs/9699919799/functions/sigwaitinfo.html)
- [Self-pipe trick](http://cr.yp.to/docs/selfpipe.html)
- [Signal-safe locks](https://locklessinc.com/articles/signalsafe_locks/)
