### ISSUE TITLE
Use as "tail -F" that displays output from stdin?

### ISSUE THREAD

**Issue by bradparks** [p-gen/smenu#14]
Is there a way to use this like a mini `tail -F`, or interactive less, so it in place shows a menu of the last 5 lines of input until input is no longer received, then it exits?

I've detailed the question here in a stackoverflow post, 

https://stackoverflow.com/questions/52536392/how-to-tail-f-but-keep-it-only-scrolling-output-in-last-5-lines/52537802#52537802

and thought that maybe smenu might do this? Thanks!

**Comment by p-gen** [comment]
I need to think about it because it requires a heavy refactoring. smenu was not created to handle an infinite stdin flow and a lot of code need to be changed to add this feature.

**Comment by bradparks** [comment]
gotcha! no worries... i just wanted to make sure i wasn't missing a way to do it. Thanks again, as smenu is *nice* !
