### ISSUE TITLE
Problems on Mac OSX and FreeBSD

### ISSUE THREAD

**Issue by dbaio** [p-gen/smenu#2]
Hi.

First of all, this is a nice tool, congrats.

I had problems on Mac OSX and FreeBSD.

FreeBSD: 

[snip]
config.status: executing depfiles commands
make  all-am
  CC       smenu.o
smenu.c: In function 'sig_handler':
smenu.c:3942:10: error: 'SIGWINCH' undeclared (first use in this function)
     case SIGWINCH:
          ^
smenu.c:3942:10: note: each undeclared identifier is reported only once for each function it appears in
smenu.c: In function 'main':
smenu.c:4972:13: error: 'SIGWINCH' undeclared (first use in this function)
   sigaction(SIGWINCH, &sa, NULL);
             ^
*** Error code 1

Stop.
make[1]: stopped in /usr/home/dbaio/FreeBSD/ports/sysutils/smenu/work/smenu-0.9.8
*** Error code 1

Stop.
make: stopped in /usr/home/dbaio/FreeBSD/ports/sysutils/smenu/work/smenu-0.9.8

Mac OSX:

[snip]
config.status: executing depfiles commands
/Library/Developer/CommandLineTools/usr/bin/make  all-am
  CC       smenu.o
smenu.c:3963:10: error: use of undeclared identifier 'SIGWINCH'
    case SIGWINCH:
         ^
smenu.c:4993:13: error: use of undeclared identifier 'SIGWINCH'
  sigaction(SIGWINCH, &sa, NULL);
            ^
2 errors generated.
make[1]: *** [smenu.o] Error 1
make: *** [all] Error 2

After see this, I builded smenu without problems:
https://github.com/martanne/vis/blob/master/configure#L213

FreeBSD:
-D__BSD_VISIBLE

MacOS:
-D_DARWIN_C_SOURCE

but now smenu is not working as on linux.

R=$(seq 600 | smenu -d -s '/190')

This above example on both MacOS and FreeBSD, freezes after one move.

I've tried different compilations on FreeBSD but the problem occurs always.

ldd /usr/local/bin/smenu
/usr/local/bin/smenu:
        libncurses.so.8 => /lib/libncurses.so.8 (0x800832000)
        libc.so.7 => /lib/libc.so.7 (0x800a86000)

ldd /usr/local/bin/smenu
/usr/local/bin/smenu:
        libtinfo.so.6 => /usr/local/lib/libtinfo.so.6 (0x800832000)
        libc.so.7 => /lib/libc.so.7 (0x800a6b000)

Do you have any thoughts or advices about this?

ps. I really want to port it on FreeBSD =)

Best regards.

**Comment by jungle-boogie** [comment]
I had the same issue on freebsd 11-release.

**Comment by p-gen** [comment]
Thank you for reporting, i'll try to fix that ASAP

**Comment by p-gen** [comment]
I pushed some new commits to try to solve the issue. Can you check them please?

**Comment by dbaio** [comment]
It worked perfectly. Thank you so much.

**Comment by dbaio** [comment]
Will you make a new release ?

**Comment by p-gen** [comment]
Soon, I'm waiting for other feedbacks.
