### ISSUE TITLE
Question about multi-select

### ISSUE THREAD

**Issue by ShawnMcCool** [p-gen/smenu#23]
I'm not sure how to select multiple entries when using -T

When I hit enter (of course) it chooses the entry and exits. Is there another selection button that I can't find in the docs?

**Comment by p-gen** [comment]
When in tag mode (-T) or in pin mode (-P) you can use the `INS`/`DEL`/`t`/`T`/`U` as indicated in the manual (**man smenu** and search **Tagging**).

E.g.:
`$ R=$(echo "A B C" | smenu -T)`
(play with `INS` and `DEL` per example, the tagged words will look underlined by default)
`$ echo $R`
(`$R` will contain the tagged words if any)

Hope this helps.

**Comment by ShawnMcCool** [comment]
Ah great, I was looking for 'select'.

Thanks for the help. Really fun / versatile little tool. =)
