### ISSUE TITLE
autoconf hardcoded version

### ISSUE THREAD

**Issue by zhum** [p-gen/smenu#27]
Now autoconf 1.16 is used and after `configure` version of `aclocal` and `automake` is hadrcoded into Makefile. If I change it to 1.13, make still works fine (Centos -7.8).

I think hardcoded autoconf version is not a good choice...

**Comment by p-gen** [comment]
Hello, these files are generated automatically by the GNU _autoconf_ program provided by my linux distribution. They are necessary for the build process. If for some reason the provided versions do not work in your use case. You can always regenerate them using your local _autoconf_ suite by entering `autoreconf -vif`

Anyway, the provided files should work regardless of the version of _autotconf_/_automake_ you have.

**Comment by zhum** [comment]
You're right. But if you just remove `-1.13` from `configure`, it would be portable and will work on any (almost) version of autoconf.

**Comment by p-gen** [comment]
The configure script is autogenerated by autoreconf and *is* portable as far as I can tell. By the way, there is no -1.13 in the last released version. Anyway, it would not have been my intention to rework an autogenerated script.
