### ISSUE TITLE
configure searches for non-existent file

### ISSUE THREAD

**Issue by jbrubake** [p-gen/smenu#30]
The configure script looks for `build-aux/compile` which does not exist. The build still completed successfully when removing the reference.

Line 2387: `ac_aux_files="config.guess config.sub compile missing install-sh"`

**Comment by jbrubake** [comment]
I should have clarified that. I did use `build.sh`.

**Comment by p-gen** [comment]
I just pushed a new commit, could you retry please? BTW What is your  compilation environment?

**Comment by jbrubake** [comment]
That fixed it.

Fedora 35
gcc-11.3.1
make-4.3

**Comment by p-gen** [comment]
Thanks for testing, glad the problem is now solved. Have fun with smenu :-)
