### ISSUE TITLE
The length of a word has reached the limit of 512 characters.

### ISSUE THREAD

**Issue by leapfog** [p-gen/smenu#31]
I tried your "Bash example (CRTL-R replacement)" with 1.0.0.RC2 but all I get after hitting Ctrl-R is "The length of a word has reached the limit of 512 characters." I do have large history files (2MB/~30,000lines and 3.6MB/80,000lines), but [`hstr`](https://github.com/dvorka/hstr) can easily handle them.

**Comment by p-gen** [comment]
Use the `w` suboption of `-lim` to increase the word limit as in `-lim w:262144` for example, the value is a long integer.

Please refer to the manual for more details.

**Comment by p-gen** [comment]
A little clarification: sub-options of `-lim` like `l` and `w` must be used together because the `-lim` option cannot be repeated. For example: `-lim l:4096 w:262144`

Another possibility is to use a configuration file as explained in the manual.
