### ISSUE TITLE
Add support prompt for multi-line text

### ISSUE THREAD

**Issue by jirutka** [p-gen/smenu#32]
Can you please consider implementing an equivalent of [gum write](https://github.com/charmbracelet/gum#write) – prompt for multi-line text?

![](https://camo.githubusercontent.com/0677059dbb13751171b25b7edf4f70ee4b01b804b94cc0876c8bd956a7647d99/68747470733a2f2f73747566662e636861726d2e73682f67756d2f77726974652e676966)

You can freely move the cursor and scroll within the box.

**Comment by p-gen** [comment]
Hello, smenu is a selection tool and does not allow you to enter arbitrary text.
