### ISSUE TITLE
Add support for fuzzy matching to filter a list of values

### ISSUE THREAD

**Issue by jirutka** [p-gen/smenu#33]
Can you please consider implementing an equivalent of [gum filter](https://github.com/charmbracelet/gum#filter)?

![](https://camo.githubusercontent.com/91a2a754c42c4922be49ba009983e8734befd3ae1c415cfe17d0878cdea5b0f4/68747470733a2f2f73747566662e636861726d2e73682f67756d2f66696c7465722e676966)

**Comment by p-gen** [comment]
Hello, the fuzzy search is already implemented, see the manual about the `/` key.
