### ISSUE TITLE
A column context but limiting how many columns are produced

### ISSUE THREAD

**Issue by Earnestly** [p-gen/smenu#37]
I have inputs which display livestreams, the view count and their title; e.g.

```
foobar 1234 title of the stream
baz 1337 another title for another stream
```

When using `-c -C1` this more or less does what I want, making only the first column selectable and producing alignment over the view count.  The problem is that the rest of the message is also aligned, which I'd like to avoid, e.g.

```
foobar | 1234 | title   | of    | the | stream
baz    | 1337 | another | title | for | another stream
```

Instead I would like something that behaves as follows:

```
foobar | 1234 | title of the stream
baz    | 1337 | another title for another stream
```

(Using `|` as a visual indicator of the columns, not much unlike `-g '|| '`)

I'm not sure if what I'm after can be done with existing features, I tried my best to look through the manual but didn't find anything particularly obvious.

**Comment by p-gen** [comment]
Hi, this is not possible at this time. This feature could be added in a future version.
However, as smenu was designed as a filter you can easily apply the unix philosophy by combining it with other commands as in the example below:

```
cat your_data_file \
| while read -r L ;do
    read A B C <<<$L
    echo $A $B \"$C\"
  done \
| smenu -c -C1 -g '|'
```

**Comment by p-gen** [comment]
By the way, `-g` displays a vertical bar separator by default, so its argument is unnecessary here.

**Comment by Earnestly** [comment]
Quotes in the input suppress this by treating a quoted region as a discrete "word"?

**Comment by p-gen** [comment]
Adding such functionality may be done later but with low priority as your problem can be easily solved by preprocessing the standard input before passing it to smenu.

Thank you for considering my small utility to solve your problem.
