### ISSUE TITLE
Segmentation fault when using hidden timeout with word

### ISSUE THREAD

**Issue by Tholleman** [p-gen/smenu#39]
```bash
$ echo "a b c" | smenu -x word d 5
# works without any problems

$ echo "a b c" | smenu -X word d 5
Segmentation fault (core dumped)

$ echo "a b c" | smenu -X current 5
# works without any problems
```

Kernel: 5.19.0-35-generic 
OS: Ubuntu 22.04.2 LTS x86_64 
Shell: bash 5.1.16

**Comment by Tholleman** [comment]
Just realized I'm using version 0.9.17 because it's been installed through apt. Maybe an update will fix it. Is there an ETA on when it will be published?

**Comment by p-gen** [comment]
No news = good news.
