### ISSUE TITLE
Selection of a directory for auxiliary build tools

### ISSUE THREAD

**Issue by elfring** [p-gen/smenu#4]
I suggest to add [the call of the macro "`AC_CONFIG_AUX_DIR`"](https://www.gnu.org/savannah-checkouts/gnu/autoconf/manual/autoconf-2.69/html_node/Input.html#index-AC_005fCONFIG_005fAUX_005fDIR-58 "Use auxiliary build tools") to [your configuration script](https://github.com/p-gen/smenu/blob/55d3516e79de3866d49644f04bab18f945181fca/configure.ac#L6 "Update candidate") so that auxiliary build tools will be stored in a dedicated directory.

**Comment by p-gen** [comment]
Thank you for your suggestion. I just pushed a commit to implement that.

**Comment by elfring** [comment]
Thanks for [your small improvement of the build scripts](https://github.com/p-gen/smenu/commit/2ca4c3261892bc056071f2eb5d6105cbe5c90f3d "Improve the configure process").
