### ISSUE TITLE
Feature request: press key to choose selection and exit without pressing ENTER

### ISSUE THREAD

**Issue by hammy0** [p-gen/smenu#40]
Hello, as I understand it if my menu has options such as "a) .. b) .. c) .." to choose one of a,b,c I have to press a then ENTER, would it be possible to press a,b or c and smenu will choose that selection and exit straight away as if ENTER has been pressed, just as q exits straight away?

**Comment by p-gen** [comment]
Hello,

The difficulty with your request is that it would only work if the words to be selected were composed of a single character.

For now, the best solution to your problem is to select the desired word by double-clicking on it with the mouse if there is one.

**Comment by hammy0** [comment]
okay thank you, I really love smenu :)
