### ISSUE TITLE
Option to start with search running

### ISSUE THREAD

**Issue by oernii** [p-gen/smenu#41]
Would it be possible to add an option, which would start the prefedined search method without pressing additional keys like "/" ? What I am trying to achieve is to be able to run smenu with some server names and directly search for substrings.

thanks.

**Comment by p-gen** [comment]
It's an interesting idea, I'll think about the best way to implement it. In the meantime, the '-s' option might be sufficient for your needs.

**Comment by p-gen** [comment]
I've added a feature to the -start option in commit d3ba828 that implements something similar to what you asked for, I invite you to take a look.
