### ISSUE TITLE
v1.3.0 not working with TERM=xterm

### ISSUE THREAD

**Issue by schorsch3000** [p-gen/smenu#42]
Hi,
i've installed smenu from smenu-1.3.0-linux-glibc-x86-static.xz 
i can't start smenu now:

```
# smenu 
'xterm': unknown terminal type.
```
According to https://github.com/p-gen/smenu/issues/16#issuecomment-436741997
xterm shout work.

If there is anything i can help, feel free to reach out!

**Comment by p-gen** [comment]
Hello,

it seems that 'xterm' is not defined in your terminfo database; this message is not displayed by smenu but by the setupterm(3) library function.

Can you tell me more about your environment?
What is the result of the command: infocmp xterm?
Does it work with TERM=vt100 or TERM=vt220 or any other terminal defined in your terminfo database (you can use the toe(1) command to get the list)?

**Comment by p-gen** [comment]
OK, so you can confirm that the command `TERM=xterm smenu` is working fine.
What does the command `terminfo xterm-kitty` reports?

BTW on debian I think you have to install the` kitty-terminfo` packages if your `TERM` variable is set to `xterm-kitty`.

**Comment by schorsch3000** [comment]
My `$TERM` is set to `xterm` not `xterm-kitty` and kitty-terminfo is installed, thanks neverless!
i don't have a command `terminfo` and no idea how to get it, the package `terminfo` dos not provide that :(

If it's a me-problem, i have no problem having a inline-wrapper-script setting `$TERM` to `vt100`

**Comment by schorsch3000** [comment]
oh, no, `TERM=xterm` dos not work, `TERM=vt100 smenu` works, as with `vt220`

**Comment by p-gen** [comment]
If `$TERM` contains `xterm`, this should work.
You can also try deleting your `~/.terminfo` directory if you have one.

As I don't understand why you can't use `TERM=xterm`, try to:
- set TERM to vt220 before using smenu (`TERM=vt220 smenu` ...).
- use a wrapper script to set `XTERM=vt220` as you said.

This is not a smenu problem but a configuration issue.

**Comment by schorsch3000** [comment]
yep, i've tried on another pc running debian and kitty, can confirm its a me-problem.
~/.terminfo isn't existent, i'll go by a wrapper script, thanks so much for the help and the whole project!

**Comment by p-gen** [comment]
you're welcome
