### ISSUE TITLE
Freezes terminal with v0.9.12 in FreeBSD

### ISSUE THREAD

**Issue by dbaio** [p-gen/smenu#7]
I've tried just the example below:
`$ R=$(awk -F: '$3 < 100 {print $1,$3,$4,$NF}' /etc/passwd \
      | smenu -n10 -c)`

<img width="648" alt="screen shot 2018-04-09 at 19 42 03" src="https://user-images.githubusercontent.com/2529335/38526833-348c92b2-3c2e-11e8-8dd2-632ee44e6a10.png">

Is there anything I can do to help in debugging?

Regards.

**Comment by p-gen** [comment]
Thank you for testing, This example is working correctly on Linux, can you reproduce your issue with an input file less sensible and join this file ?

**Comment by dbaio** [comment]
Sure, you can test with this UID file from FreeBSD Ports 
https://raw.githubusercontent.com/freebsd/freebsd-ports/master/UIDs


`R=$(cat /tmp/UIDs | egrep -v '^#' | awk -F: '$3 < 100 {print $1,$3,$4,$NF}' | less | smenu -n10 -c)`

**Comment by p-gen** [comment]
smenu is working correctly with your file on Linux, i'll try to install a FreeBSD VM to try to reproduce your issue.
![capture du 2018-04-10 14-46-04](https://user-images.githubusercontent.com/12358332/38557637-ee0105bc-3ccd-11e8-8844-0cfe47a38fdf.png)
![capture du 2018-04-10 14-52-33](https://user-images.githubusercontent.com/12358332/38557907-d354c108-3cce-11e8-89e7-61f2f6a0a3a2.png)

Regards.

**Comment by p-gen** [comment]
I think I've found the problem. Working on a fix

**Comment by p-gen** [comment]
Can you retry after having applied this patch please? [freebsd.patch.zip](https://github.com/p-gen/smenu/files/1905307/freebsd.patch.zip)

**Comment by dbaio** [comment]
It worked perfectly.
Thank you!

**Comment by p-gen** [comment]
Fine, I must refine that though. I'll tag a new release in two or three weeks as there are some remaining things to add and improve.

BTW, do you have the opportunity to test smenu on other BSD-based Unix?

**Comment by dbaio** [comment]
Great, thanks!
I can create some VMs and test it, I'll let you know.

**Comment by p-gen** [comment]
I pushed some new commits. The first two should hopefully resolve this issue. Could you please confirm that please?

**Comment by dbaio** [comment]
Everything great with the latest commit. https://github.com/p-gen/smenu/commit/0ff0326b7084e5f91f6b02bc9baec49bdeb5e6c7
Thanks again for your time and work.

**Comment by p-gen** [comment]
Thank you for the feedback.
